#!/bin/bash

ip=$1
ct=$2
outfile=$3 

if [[ $ct == "" ]]; then echo "usage: $0 count outfile"; exit 1; fi

if [[ $outfile == "" ]]; then
	ping -c$ct $ip |  awk '{ split($5, a, "="); split($7, b, "="); if (a[2]!="") print a[2]","b[2] }'
else
	echo "writing to $outfile..";
	> $outfile
	ping -c$ct $ip |  awk '{ split($5, a, "="); split($7, b, "="); if (a[2]!="") print a[2]","b[2] }' >> $outfile
fi

